title: Muhammad Hamdan # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an Automation Engineer with over 4 years of experience. I have diverse set of skills ranging 
  from systems automation to autonomy. I am currently researching deep learning models to quantify 
  and characterize material in images. My key competences include systems automation and instrumentation,
  deep learning application centric model development, computer vision algorithms, and hardware acceleration
  of computer vision and machine learning algorithms.
  <br><br>
  <a href="https://linkedin.com/in/muhammad-hamdan-6b4a8b71/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-148376793-1 # your Google Analytics tracking ID here
